/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.util.LinkedList;

/**
 *
 * @author User
 */
public class Grafik extends javax.swing.JFrame {

        //Titik a = new Titik(20,10,"A",1);
        //Garis A = new Garis(1,2,"Jl Arif Rahman Hakim",4);
        LinkedList<Titik> kumpulanTitik = new LinkedList<Titik>();
        LinkedList<Garis> kumpulanGaris = new LinkedList<Garis>();
        double mapwidth = 400;
        double mapheight = 400;
    /**
     * Creates new form Grafik
     */
    public Grafik() {
        initComponents();
        koleksiTitik();
        koleksiGaris();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        test();
            
            
        }
    // TODO add your handling code here:

    private void test() {
        Garis A;
        for (int i = 0; i < kumpulanGaris.size(); i++) {
            A = kumpulanGaris.get(i);
            System.out.println(A.getAwal()+","+A.getAkhir()+","+A.getLabel()+","+A.getJarak());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    private void koleksiTitik() {
        kumpulanTitik.add(new Titik(-7.112551, 112.417222, "Adipura"));
        kumpulanTitik.add(new Titik(-7.120135, 112.415562, "AlunAlun"));
        kumpulanTitik.add(new Titik(-7.113087, 112.419886, "LP"));
        kumpulanTitik.add(new Titik(-7.114702, 112.423005, "SMADALA"));
        kumpulanTitik.add(new Titik(-7.119461, 112.422705, "SMASALA"));
        kumpulanTitik.add(new Titik(-7.121473, 112.418992, "Warkop"));
        kumpulanTitik.add(new Titik(-7.122409, 112.422340, "UNISLA"));
    }
    
    public void paint(Graphics g){
        Graphics2D g2 = (Graphics2D) g;
        tampil(g2);
        tampilGaris(g2);
    }
    
    private void tampil(Graphics2D g2){
        Titik A;
        double x,y;
        for (int i = 0; i < kumpulanTitik.size(); i++) {
            A = kumpulanTitik.get(i);
            //System.out.println(A.getX()+","+A.getY()+","+A.getLabel()+","+A.getNomor());
            x = konversiLonkeX(A.getX());
            y = konversiLatkeY(A.getY());
            g2.draw(new Ellipse2D.Double((int) x,(int) y,5,5));
            //g2.drawString(A.getLabel(),A.getX(),A.getY());
        }
    }
    
    private void tampilGaris(Graphics2D g2){
        Garis A;
        Titik Awal, Akhir;
        int x1, y1, x2, y2;
        for (int i = 0; i < kumpulanGaris.size(); i++) {
            A = kumpulanGaris.get(i);
            //System.out.println(A.getAwal()+","+A.getAkhir()+","+A.getLabel()+","+A.getJarak());
            Awal = kumpulanTitik.get(A.getAwal()-1);
            Akhir = kumpulanTitik.get(A.getAkhir()-1);
            x1 = Awal.getX();
            y1 = Awal.getY();
            x2 = Akhir.getX();
            y2 = Akhir.getY();
            g2.draw(new Line2D.Double(x1, y1, x2, y2));
            
    }
    }

    private void koleksiGaris() {
        kumpulanGaris.add(new Garis(0,1,"Apple"));
        kumpulanGaris.add(new Garis(1,2,"Samsung"));
        kumpulanGaris.add(new Garis(0,6,"Lenovo"));
        kumpulanGaris.add(new Garis(1,6,"Toshiba"));
        kumpulanGaris.add(new Garis(2,3,"Asus"));
        kumpulanGaris.add(new Garis(3,4,"Sony"));
        kumpulanGaris.add(new Garis(4,5,"Dell"));
        kumpulanGaris.add(new Garis(5,6,"Allien War"));
    }
    
    private double konversiLonkeX(double lon) {
        double x = (180+lon) * (mapwidth / 360)*10000;
        return x;
        
    }

    private double konversiLatkeY(double lat) {
        double y = (90-lat) * (mapheight / 180)*10000;
        return y;
    }
}
